"""
IT 뉴스 다이제스트 — 로컬 크론 자동화 스크립트
crontab: 0 10 * * * /usr/bin/python3 /home/user/news_digest.py

필요 패키지: pip install requests python-dotenv
환경변수 (.env):
  ANTHROPIC_API_KEY=sk-ant-...
  RECIPIENT_EMAIL=your@email.com
"""

import os, json, requests
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

API_URL = "https://api.anthropic.com/v1/messages"
API_KEY = os.environ["ANTHROPIC_API_KEY"]
RECIPIENT = os.environ["RECIPIENT_EMAIL"]
TODAY = datetime.now().strftime("%Y-%m-%d")

HEADERS = {
    "Content-Type": "application/json",
    "x-api-key": API_KEY,
    "anthropic-version": "2023-06-01",
    # MCP 커넥터에 필요. raw HTTP이므로 본문이 아니라 헤더로 보낸다.
    "anthropic-beta": "mcp-client-2025-11-20",
}


def call_api(body: dict) -> dict:
    r = requests.post(API_URL, headers=HEADERS, json=body, timeout=120)
    r.raise_for_status()
    return r.json()


# ── 1. 오케스트레이터: 뉴스 수집 ──────────────────────────────────────────
def fetch_news() -> dict:
    data = call_api({
        "model": "claude-sonnet-4-20250514",
        "max_tokens": 2000,
        "system": (
            "당신은 IT 뉴스 큐레이터입니다. 반드시 순수 JSON만 반환:\n"
            '{"date":"YYYY-MM-DD",'
            '"ai_news":[{"title":"...","summary":"2-3문장","source":"출처명"}],'
            '"tech_news":[{"title":"...","summary":"2-3문장","source":"출처명"}]}\n'
            "ai_news 4개, tech_news 4개."
        ),
        "tools": [{"type": "web_search_20250305", "name": "web_search"}],
        "messages": [{"role": "user", "content": f"{TODAY} 최신 AI 및 IT 테크 뉴스를 검색해서 JSON으로 요약해줘."}]
    })
    text = next((b["text"] for b in data["content"] if b["type"] == "text"), "{}")
    return json.loads(text.replace("```json", "").replace("```", "").strip())


# ── 2. 서브 에이전트 A: Notion 저장 ───────────────────────────────────────
def save_to_notion(news: dict) -> str:
    content = f"## AI 뉴스\n"
    for i, n in enumerate(news.get("ai_news", []), 1):
        content += f"{i}. **{n['title']}**\n{n['summary']}\n출처: {n['source']}\n\n"
    content += "## 테크 뉴스\n"
    for i, n in enumerate(news.get("tech_news", []), 1):
        content += f"{i}. **{n['title']}**\n{n['summary']}\n출처: {n['source']}\n\n"

    data = call_api({
        "model": "claude-sonnet-4-20250514",
        "max_tokens": 800,
        "mcp_servers": [{"type": "url", "url": "https://mcp.notion.com/mcp", "name": "notion-mcp"}],
        "tools": [{"type": "mcp_toolset", "mcp_server_name": "notion-mcp"}],
        "messages": [{"role": "user", "content":
            f"다음 뉴스 요약을 Notion에 저장해주세요.\n"
            f"제목: 📰 IT 뉴스 요약 - {TODAY}\n\n{content}\n\n"
            "워크스페이스에서 뉴스 관련 페이지/DB를 찾거나 없으면 루트에 새 페이지 생성."
        }]
    })
    return next((b["text"] for b in data["content"] if b["type"] == "text"), "완료")


# ── 3. 서브 에이전트 B: Gmail 드래프트 ────────────────────────────────────
def send_email_draft(news: dict) -> str:
    items_html = ""
    for section, label, color in [("ai_news", "AI 뉴스", "#3C3489"), ("tech_news", "테크 뉴스", "#0F6E56")]:
        items_html += f'<h2 style="color:{color};font-size:14px;border-bottom:1px solid #eee;padding-bottom:8px">{label}</h2>'
        for i, n in enumerate(news.get(section, []), 1):
            items_html += (
                f'<div style="margin-bottom:14px">'
                f'<p style="font-size:14px;font-weight:600;margin:0 0 4px">{i}. {n["title"]}</p>'
                f'<p style="font-size:13px;color:#555;margin:0 0 4px;line-height:1.6">{n["summary"]}</p>'
                f'<p style="font-size:11px;color:#999;font-family:monospace;margin:0">출처: {n["source"]}</p>'
                f'</div>'
            )

    email_html = (
        f'<div style="font-family:sans-serif;max-width:600px;margin:0 auto">'
        f'<div style="background:#1a1a1a;padding:20px 24px;border-radius:8px 8px 0 0">'
        f'<p style="color:#EF9F27;font-family:monospace;font-size:11px;margin:0 0 4px">DAILY IT NEWS DIGEST</p>'
        f'<h1 style="color:#fff;font-size:20px;margin:0;font-weight:500">📰 IT 뉴스 요약</h1>'
        f'<p style="color:#888;font-size:13px;margin:4px 0 0">{TODAY}</p>'
        f'</div>'
        f'<div style="border:1px solid #e5e5e5;border-top:none;padding:20px 24px;border-radius:0 0 8px 8px">'
        f'{items_html}'
        f'<p style="font-size:11px;color:#bbb;font-family:monospace;margin-top:16px">Generated by Clo · infoloomia</p>'
        f'</div></div>'
    )

    data = call_api({
        "model": "claude-sonnet-4-20250514",
        "max_tokens": 800,
        "mcp_servers": [{"type": "url", "url": "https://gmailmcp.googleapis.com/mcp/v1", "name": "gmail-mcp"}],
        "tools": [{"type": "mcp_toolset", "mcp_server_name": "gmail-mcp"}],
        "messages": [{"role": "user", "content":
            f"수신자: {RECIPIENT}\n제목: 📰 IT 뉴스 요약 - {TODAY}\nHTML 본문:\n{email_html}\n\n드래프트로 저장해줘."
        }]
    })
    return next((b["text"] for b in data["content"] if b["type"] == "text"), "완료")


# ── 메인 ──────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print(f"[{TODAY}] 뉴스 수집 시작...")
    news = fetch_news()
    print(f"  AI {len(news.get('ai_news', []))}건, 테크 {len(news.get('tech_news', []))}건 수집")

    # 서브 에이전트 순차 실행 (cron 환경에서는 스레드 없이)
    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=2) as ex:
        f_notion = ex.submit(save_to_notion, news)
        f_mail   = ex.submit(send_email_draft, news)
        print("  Notion:", f_notion.result()[:60])
        print("  Gmail:",  f_mail.result()[:60])

    print("완료.")
